/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.1.184
 Source Server Type    : MySQL
 Source Server Version : 50633
 Source Host           : 192.168.1.184
 Source Database       : irenshi

 Target Server Type    : MySQL
 Target Server Version : 50633
 File Encoding         : utf-8

 Date: 12/13/2019 15:39:23 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `tab_staff_info`
-- ----------------------------
DROP TABLE IF EXISTS `tab_staff_info`;
CREATE TABLE `tab_staff_info` (
  `id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_date` datetime DEFAULT NULL,
  `isDeleted` bit(1) DEFAULT NULL,
  `basicInfo1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `basicInfo2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birthday` datetime DEFAULT NULL,
  `bloodType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `calculationTime` datetime DEFAULT NULL,
  `childName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `childName2` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contractType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleteDate` datetime DEFAULT NULL,
  `departmentId` bigint(20) DEFAULT NULL,
  `departmentName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergencyContactMobile` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergencyContactName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enrollInDate` datetime DEFAULT NULL,
  `enrollStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `highestEducation` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `houseFundBeginMonth` datetime DEFAULT NULL,
  `houseFundCityCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `houseFundEndMonth` datetime DEFAULT NULL,
  `houseFundNo` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `houseFundProvinceCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo1` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo2` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo3` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo4` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo5` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hukouAddress` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hukouCityCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hukouProvinceCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hukouType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idCardImageId1` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idCardImageId2` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idCardImageId3` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idCardNo` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `idCardType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDepartmentManager` bit(1) DEFAULT NULL,
  `lastWorkDay` datetime DEFAULT NULL,
  `leaveDate` datetime DEFAULT NULL,
  `livingAddress` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `livingCityCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `livingProvinceCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `marryStatus` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobileNo` varchar(18) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nationality` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nativePlace` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nativePlaceCityCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nativePlaceProvinceCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nickName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `politicalStatus` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `positionId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `positionLevelId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `positionLevelName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `positionName` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `probationLength` int(11) DEFAULT NULL,
  `probationSalary` decimal(19,2) DEFAULT NULL,
  `quitType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `regularSalary` decimal(19,2) DEFAULT NULL,
  `relateTime` datetime DEFAULT NULL,
  `replenishHouseFundNo` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sex` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `socialInsuranceAccountNo` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `socialInsureBeginMonth` datetime DEFAULT NULL,
  `socialInsureCityCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `socialInsureEndMonth` datetime DEFAULT NULL,
  `socialInsureProvinceCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `spouseName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `staffName` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL,
  `staffNo` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `staffStatus` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `staffType` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `workEmail` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `workPhone` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `workPlace` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `workYears` double DEFAULT NULL,
  `staffOrigin` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firstWorkYears` double DEFAULT NULL,
  `initialWorkYears` double DEFAULT NULL,
  `enrollInDateBefore` datetime DEFAULT NULL,
  `userId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hideDetailInApp` bit(1) DEFAULT NULL,
  `staffImageId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enrollWorkYears` double DEFAULT NULL,
  `enclosureId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `staffRemark` text COLLATE utf8mb4_unicode_ci,
  `contractLength` int(11) DEFAULT NULL,
  `hrInfo10` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo11` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo12` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo13` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo14` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo15` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo16` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo17` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo18` text COLLATE utf8mb4_unicode_ci,
  `hrInfo19` text COLLATE utf8mb4_unicode_ci,
  `hrInfo20` text COLLATE utf8mb4_unicode_ci,
  `hrInfo6` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo7` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo8` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrInfo9` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quitReason` varchar(1200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRelatedApp` bit(1) DEFAULT NULL,
  `canViewAddressBook` bit(1) DEFAULT NULL,
  `qqNo` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weChatNo` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contractBeginDate` datetime DEFAULT NULL,
  `contractEndDate` datetime DEFAULT NULL,
  `probationEndDate` datetime DEFAULT NULL,
  `canViewFirstLevelDepartment` bit(1) DEFAULT NULL,
  `firstLevelDepartmentId` bigint(20) DEFAULT NULL,
  `firstLevelDepartmentName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `viewAddressBookType` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quitReasonType` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quitRemindStaff` text COLLATE utf8mb4_unicode_ci,
  `dingId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentSequence` bigint(20) DEFAULT NULL,
  `sequence` bigint(20) DEFAULT NULL,
  `quitImageIds` text COLLATE utf8mb4_unicode_ci,
  `imId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currentSalary` decimal(19,2) DEFAULT NULL,
  `isUseLunar` bit(1) DEFAULT NULL,
  `lunarBirthdayDay` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lunarBirthdayMonth` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lunarBirthdayYear` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nextSolarBirthday` date DEFAULT NULL,
  `serialNumber` int(11) DEFAULT NULL,
  `taxAt` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `taxRole` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isReinstate` bit(1) DEFAULT NULL,
  `reinstateType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reinstateNumber` int(11) DEFAULT NULL,
  `jobTitleId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jobTitleName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companySiteId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `showInAppType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companySiteName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `insureDefinitionId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firstName` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastName` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `legalName` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `socialInsureAreaCode` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corporationId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corporationName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyTaxInformationId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subCompanyName` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyTaxInformationName` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supervisorId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `immediateSupervisorId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supervisorName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `immediateSupervisorName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subCompanyId` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRegisterImId` bit(1) DEFAULT NULL,
  `isProbation` bit(1) DEFAULT NULL,
  `isSyncRosterAccount` bit(1) DEFAULT b'0',
  `positiveDate` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tab_staff_info_companyId_mobileNo_status_index` (`companyId`,`mobileNo`,`staffStatus`),
  KEY `idx_tab_staff_info_departmentId_sequence` (`departmentId`,`sequence`),
  KEY `idx_mob_status` (`mobileNo`,`staffStatus`,`enrollStatus`(191)),
  KEY `idx_imid` (`imId`),
  KEY `idx_compId_departmentId` (`companyId`,`departmentId`),
  KEY `company_staff_status_index` (`companyId`,`staffStatus`,`enrollStatus`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
